---
- name: Gather active sessions
  ansible.builtin.command:
    cmd: who
  register: active_sessions
  changed_when: false

- name: Parse and filter physical console (tty) sessions
  ansible.builtin.set_fact:
    tty_sessions_raw: >-
      {{
        active_sessions.stdout_lines
        | select('regex', '^\\S+\\s+tty')
        | list
      }}

- name: Initialize temporary empty list for TTY sessions with hostname
  ansible.builtin.set_fact:
    _tty_sessions: []

- name: Create temporary custom list of TTY sessions with hostname
  ansible.builtin.set_fact:
    _tty_sessions: >-
      {{
        _tty_sessions
        + [
            {
              'host': inventory_hostname,
              'username': item.split()[0],
              'tty': item.split()[1],
              'login_date': item.split()[2] + ' ' + item.split()[3]
            }
          ]
      }}
  loop: "{{ tty_sessions_raw }}"
  loop_control:
    label: "{{ inventory_hostname }}"
  when: tty_sessions_raw | length > 0

- name: Combine all sessions into one list
  ansible.builtin.set_fact:
    tty_sessions: >-
      {{
        hostvars
        | dict2items
        | map(attribute='value._tty_sessions')
        | select('defined')
        | flatten
        | list
      }}

- name: Output TTY sessions
  ansible.builtin.debug:
    var: tty_sessions
  delegate_to: localhost
  run_once: true  # noqa run-once[task]
  when: tty_sessions | length > 0

- name: Include email reporting tasks
  ansible.builtin.include_tasks:
    file: email.yml
